// Bibliothèque de 15 vidéos — partagée entre Dashboard et Room
export const VIDEO_LIBRARY = [
  {
    id: 'v01', title: 'Big Buck Bunny',
    description: 'Un lapin géant affronte trois rongeurs malveillants dans une forêt enchantée.',
    genre: 'Animation · Comédie', year: 2008, duration: '10 min',
    type: 'hls', url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/220px-Big_buck_bunny_poster_big.jpg',
    color: '#4f46e5',
  },
  {
    id: 'v02', title: 'Sintel',
    description: 'Une jeune femme part en quête d\'un bébé dragon qu\'elle a apprivoisé.',
    genre: 'Animation · Fantastique', year: 2010, duration: '14 min',
    type: 'youtube', videoId: 'eRsGyueVLvQ',
    thumbnail: 'https://img.youtube.com/vi/eRsGyueVLvQ/mqdefault.jpg',
    color: '#7c3aed',
  },
  {
    id: 'v03', title: 'Tears of Steel',
    description: 'Des robots envahisseurs menacent l\'humanité dans un Amsterdam futuriste.',
    genre: 'Sci-Fi · Action', year: 2012, duration: '12 min',
    type: 'youtube', videoId: 'R6MlUcmOul8',
    thumbnail: 'https://img.youtube.com/vi/R6MlUcmOul8/mqdefault.jpg',
    color: '#1d4ed8',
  },
  {
    id: 'v04', title: 'Elephants Dream',
    description: 'Le premier film open source de la Fondation Blender.',
    genre: 'Animation · Mystère', year: 2006, duration: '11 min',
    type: 'youtube', videoId: '_EVETFmP1L4',
    thumbnail: 'https://img.youtube.com/vi/_EVETFmP1L4/mqdefault.jpg',
    color: '#065f46',
  },
  {
    id: 'v05', title: 'Cosmos Laundromat',
    description: 'Une brebis solitaire rencontre un être mystérieux sur une île déserte.',
    genre: 'Animation · Drame', year: 2015, duration: '13 min',
    type: 'youtube', videoId: 'Y-rmzh0PI3c',
    thumbnail: 'https://img.youtube.com/vi/Y-rmzh0PI3c/mqdefault.jpg',
    color: '#92400e',
  },
  {
    id: 'v06', title: 'Agent 327',
    description: 'Un agent secret affronte une barbière fatale dans Amsterdam.',
    genre: 'Animation · Espionnage', year: 2017, duration: '4 min',
    type: 'youtube', videoId: 'mN0zPOpADL4',
    thumbnail: 'https://img.youtube.com/vi/mN0zPOpADL4/mqdefault.jpg',
    color: '#991b1b',
  },
  {
    id: 'v07', title: 'Sprite Fright',
    description: 'Un groupe d\'amis rencontre des créatures des bois plus dangereuses que prévu.',
    genre: 'Animation · Horreur', year: 2021, duration: '8 min',
    type: 'youtube', videoId: '_cMxraX_5RE',
    thumbnail: 'https://img.youtube.com/vi/_cMxraX_5RE/mqdefault.jpg',
    color: '#166534',
  },
  {
    id: 'v08', title: 'Charge',
    description: 'Un super-héros découvre le sens véritable de son pouvoir.',
    genre: 'Animation · Super-héros', year: 2022, duration: '4 min',
    type: 'youtube', videoId: 'UXqq0ZvbOnk',
    thumbnail: 'https://img.youtube.com/vi/UXqq0ZvbOnk/mqdefault.jpg',
    color: '#b45309',
  },
  {
    id: 'v09', title: 'Coffee Run',
    description: 'Une course effrénée pour un café dans les rues d\'une ville futuriste.',
    genre: 'Animation · Action', year: 2020, duration: '3 min',
    type: 'youtube', videoId: 'YE7VzlLtp-4',
    thumbnail: 'https://img.youtube.com/vi/YE7VzlLtp-4/mqdefault.jpg',
    color: '#7e22ce',
  },
  {
    id: 'v10', title: 'Wing It',
    description: 'Deux pélicans tentent de pêcher leur repas quotidien.',
    genre: 'Animation · Comédie', year: 2020, duration: '3 min',
    type: 'youtube', videoId: 'd2FEfgJxFXM',
    thumbnail: 'https://img.youtube.com/vi/d2FEfgJxFXM/mqdefault.jpg',
    color: '#0e7490',
  },
  {
    id: 'v11', title: 'Hero',
    description: 'Un robot répare inlassablement les dommages causés par les humains.',
    genre: 'Animation · Émouvant', year: 2018, duration: '1 min',
    type: 'youtube', videoId: 'pKmSdY56VtY',
    thumbnail: 'https://img.youtube.com/vi/pKmSdY56VtY/mqdefault.jpg',
    color: '#be185d',
  },
  {
    id: 'v12', title: 'Caminandes: Llama Drama',
    description: 'Un lama tente de traverser une propriété privée gardée par un Kiwi.',
    genre: 'Animation · Comédie', year: 2013, duration: '2 min',
    type: 'youtube', videoId: 'SkVqJ1SGeL0',
    thumbnail: 'https://img.youtube.com/vi/SkVqJ1SGeL0/mqdefault.jpg',
    color: '#15803d',
  },
  {
    id: 'v13', title: 'Cosmos Laundromat : Pilot',
    description: 'Épisode pilote du projet Cosmos Laundromat de Blender Institute.',
    genre: 'Animation · SF', year: 2015, duration: '12 min',
    type: 'youtube', videoId: 'cBTMnLYzQnA',
    thumbnail: 'https://img.youtube.com/vi/cBTMnLYzQnA/mqdefault.jpg',
    color: '#1e3a5f',
  },
  {
    id: 'v14', title: 'Glass Half',
    description: 'Un homme trouvé dans le désert raconte une histoire fascinante.',
    genre: 'Court-métrage · Drame', year: 2020, duration: '6 min',
    type: 'youtube', videoId: 'Wf1kHLFKBmk',
    thumbnail: 'https://img.youtube.com/vi/Wf1kHLFKBmk/mqdefault.jpg',
    color: '#3b0764',
  },
  {
    id: 'v15', title: 'Blender Demo Reel',
    description: 'Compilation des meilleures créations de la communauté Blender 2023.',
    genre: 'Démonstration · Art', year: 2023, duration: '5 min',
    type: 'youtube', videoId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg',
    color: '#713f12',
  },
];

export function findVideo(id) {
  return VIDEO_LIBRARY.find(v => v.id === id) || null;
}
